:toc: macro
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= Changelog

== Unreleased

* Fixes:
** Fix transport order withdrawal after order rejections.
** Avoid NullPointerExceptions in a couple of places.
** Correctly compute the sequence ID for horizon elements.
** When checking whether all nodes and edges of an order have been completed, ignore the horizon.

== Version 0.13 (2023-09-25)

* New features and enhancements:
** A vehicle's prospective route is included as the horizon in every order message.
   How many route steps are added to the horizon can be configured using the new vehicle property `vda5050:maxStepsHorizon`.
   For consistent naming, the existing property `vda5050:orderQueueSize` has been renamed to `vda5050:maxStepsBase`.
** Improve logging related to communication with vehicles.
* Other changes:
** Update Gradle wrapper to 8.3.
** Update JUnit to 5.10.0.
** Update Mockito to 5.5.0.
** Update ApprovalTests to 19.0.0.
** Update Checkstyle to 10.12.3.
** Update JaCoCo log plugin to 3.1.0.

== Version 0.12 (2023-07-24)

* New features and enhancements:
** Publish a user notification to the kernel when the vehicle rejects an order.
** Fall back to the last known position when other methods of determining the vehicle position fail.
** When the vehicle's reported operating mode changes, optionally withdraw its transport order and/or update its integration level and/or reset its last known position.
** Show the MQTT topic name prefix used for communicating with the vehicle in the driver's KCC control panel.
* Fixes:
** Send order and instant action messages to the vehicle only as long as its reported operating mode is `AUTOMATIC` or `SEMIAUTOMATIC`.
   For other operating modes, keep the messages to be sent later.
** Stop setting a vehicle's state to `UNAVAILABLE` when it reports `SEMIAUTOMATIC` as its operating mode.
   This allows vehicles in operating mode `SEMIAUTOMATIC` to process transport orders.
* Other changes:
** Update Jackson to 2.15.2.
** Update everit-json-schema to 1.14.2.
** Update JUnit 5 to 5.9.3.
** Update ApprovalTests to 18.7.1.

== Version 0.11 (2023-06-01)

* New features and enhancements:
** When receiving a state message from a vehicle, update the vehicle length with the kernel based on whether loads are reported in the state message or not.
   Allow configuration of the vehicle length that is set via vehicle properties with keys `vda5050:vehicleLengthLoaded` and `vda5050:vehicleLengthUnloaded`.
** Log MQTT client ID when connecting to broker.
* Other changes:
** Update openTCS baseline dependency to 5.9.

== Version 0.10 (2023-05-26)

* New features and enhancements:
** Add initial support for VDA5050 2.0.
   (All features supported for 1.1 are also supported for 2.0; information provided by vehicles via factsheet messages is ignored.)
** Improve JSON validation exception content by including some more information about what caused the validation to fail.

== Version 0.9 (2023-03-23)

* Initial version of the driver with support for VDA5050 1.1.
