:toc: macro
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= Changelog

== Unreleased

* New features and enhancements:
** Publish a user notification to the kernel when the vehicle rejects an order.
** Fall back to the last known position when other methods of determining the vehicle position fail.
...

== Version 0.11 (2023-06-01)

* New features and enhancements:
** When receiving a state message from a vehicle, update the vehicle length with the kernel based on whether loads are reported in the state message or not.
   Allow configuration of the vehicle length that is set via vehicle properties with keys `vda5050:vehicleLengthLoaded` and `vda5050:vehicleLengthUnloaded`.
** Log MQTT client ID when connecting to broker.
* Other changes:
** Update openTCS baseline dependency to 5.9.

== Version 0.10 (2023-05-26)

* New features and enhancements:
** Add initial support for VDA5050 2.0.
   (All features supported for 1.1 are also supported for 2.0; information provided by vehicles via factsheet messages is ignored.)
** Improve JSON validation exception content by including some more information about what caused the validation to fail.

== Version 0.9 (2023-03-23)

* Initial version of the driver with support for VDA5050 1.1.
