:doctype: book
:toc: macro
:toclevels: 6
:sectnums: all
:sectnumlevels: 6
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= Changelog

== Unreleased

* New features and enhancements:
** Allow `null` for optional properties in JSON messages.
** Support action mapping for transport order destinations.
** Fields that are marked as `NOT_SUPPORTED` via a vehicle's properties are now removed from order messages sent to that vehicle.
* Fixes:
** Some of the fields that are optional according to the VDA5050 specification are now also correctly treated as such in the driver implementations.
* Changes affecting developers:
** Update Gradle wrapper to 8.7.

== Version 0.19 (2024-03-22)

* New features and enhancements:
** In case the property `vda5050:vehicleLengthLoaded` or `vda5050:vehicleLengthUnloaded` is not set, the vehicle length configured in the plant model is used as the default value for the respective property.
* Fixes:
** Dont send cancel order actions when the vehicles changes its operating mode and is actively rejecting an order.
* Changes affecting developers:
** Update JUnit to 5.10.1.
** Update ApprovalTests to 22.3.3.
** Update Mockito to 5.8.0.

== Version 0.18 (2023-12-15)

* New features and enhancements:
** Always consider both edgeStates and nodeStates when checking whether the final movement of an order has been completed.

== Version 0.17 (2023-11-22)

* New features and enhancements:
** Check vehicle property `vda5050:movementCommandCompletedCondition` to decide when a movement command should be considered complete.
** Introduce vehicle property `vda5050:extendedDeviationRangePadding` to make the padding distance added to the extended deviation range of a node configurable.

== Version 0.16 (2023-10-30)

* New features and enhancements:
** When extending the allowed deviation radius for the first node on a route to include the vehicle position, ensure that it is really only extended but never reduced.
   I.e. always use the deviation of the node as the minimum allowed deviation, even if the vehicle is closer than that to the node's coordinates.
* Changes affecting developers:
** Update Gradle wrapper to 8.4.
** Update Jackson to 2.15.3.
** Update everit-json-schema to 1.14.3.
** Update Checkstyle to 10.12.4.
** Update Mockito to 5.6.0.
** Update ApprovalTests to 22.2.0.

== Version 0.15 (2023-10-26)

* New features and enhancements:
** When resolving the vehicle's reported position to a point in the plant model, consider the `mapId`, too.
** The paused state and informational messages are now mapped to a vehicle's properties using the keys `vda5050:paused`, `vda5050:information.info` and `vda5050:information.debug`.
* Fixes:
** Actually accept state messages lacking the `paused` flag.
** If configured, correctly withdraw the transport order assigned to a vehicle when its operation mode changes.
* Other changes:
** Update openTCS baseline dependency to 5.11.0.

== Version 0.14 (2023-09-26)

* Fixes:
** Fix transport order withdrawal after order rejections.
** Avoid NullPointerExceptions in a couple of places.
** Correctly compute the sequence ID for horizon elements.
** When checking whether all nodes and edges of an order have been completed, ignore the horizon.

== Version 0.13 (2023-09-25)

* New features and enhancements:
** A vehicle's prospective route is included as the horizon in every order message.
   How many route steps are added to the horizon can be configured using the new vehicle property `vda5050:maxStepsHorizon`.
   For consistent naming, the existing property `vda5050:orderQueueSize` has been renamed to `vda5050:maxStepsBase`.
** Improve logging related to communication with vehicles.
* Other changes:
** Update Gradle wrapper to 8.3.
** Update JUnit to 5.10.0.
** Update Mockito to 5.5.0.
** Update ApprovalTests to 19.0.0.
** Update Checkstyle to 10.12.3.
** Update JaCoCo log plugin to 3.1.0.

== Version 0.12 (2023-07-24)

* New features and enhancements:
** Publish a user notification to the kernel when the vehicle rejects an order.
** Fall back to the last known position when other methods of determining the vehicle position fail.
** When the vehicle's reported operating mode changes, optionally withdraw its transport order and/or update its integration level and/or reset its last known position.
** Show the MQTT topic name prefix used for communicating with the vehicle in the driver's KCC control panel.
* Fixes:
** Send order and instant action messages to the vehicle only as long as its reported operating mode is `AUTOMATIC` or `SEMIAUTOMATIC`.
   For other operating modes, keep the messages to be sent later.
** Stop setting a vehicle's state to `UNAVAILABLE` when it reports `SEMIAUTOMATIC` as its operating mode.
   This allows vehicles in operating mode `SEMIAUTOMATIC` to process transport orders.
* Other changes:
** Update Jackson to 2.15.2.
** Update everit-json-schema to 1.14.2.
** Update JUnit 5 to 5.9.3.
** Update ApprovalTests to 18.7.1.

== Version 0.11 (2023-06-01)

* New features and enhancements:
** When receiving a state message from a vehicle, update the vehicle length with the kernel based on whether loads are reported in the state message or not.
   Allow configuration of the vehicle length that is set via vehicle properties with keys `vda5050:vehicleLengthLoaded` and `vda5050:vehicleLengthUnloaded`.
** Log MQTT client ID when connecting to broker.
* Other changes:
** Update openTCS baseline dependency to 5.9.

== Version 0.10 (2023-05-26)

* New features and enhancements:
** Add initial support for VDA5050 2.0.
   (All features supported for 1.1 are also supported for 2.0; information provided by vehicles via factsheet messages is ignored.)
** Improve JSON validation exception content by including some more information about what caused the validation to fail.

== Version 0.9 (2023-03-23)

* Initial version of the driver with support for VDA5050 1.1.
