:toc: macro
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= Contributing to the openTCS VDA5050 driver

The following is a set of guidelines for contributing to openTCS.

This project is maintained by the openTCS development team of https://www.iml.fraunhofer.de/en.html[Fraunhofer IML].
A public mirror of the development repository is available at https://github.com/opentcs/opentcs-commadapter-vda5050[GitHub].

You are very welcome to contribute to this project when you find a bug, want to suggest an improvement, or have an idea for a useful feature.
For this, please always create an issue and/or a pull request, and follow our style guides as described below.

== Changelog

We document changes in the link:./CHANGELOG.adoc[changelog].

== Issues

It is required to create an issue if you want to integrate a bugfix, improvement, or feature.
Briefly and clearly describe the purpose of your contribution in the corresponding issue, using the appropriate template for it.

== Versioning

The openTCS project uses the https://semver.org/[SemVer] for versioning.
The release versions are tagged with their respective version.
