// SPDX-FileCopyrightText: The openTCS Authors
// SPDX-License-Identifier: CC-BY-4.0

:doctype: book
:toc: macro
:toclevels: 6
:sectnums: all
:sectnumlevels: 6
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]

= VDA5050 1.1 driver configuration

The driver reads configuration data from properties of the vehicle element in the plant model.
It reads the properties with the following keys:

`vda5050:interfaceName` (required)::
The property value contains the interface name to be used as part of the MQTT topic, e.g. `uagv`.
`vda5050:manufacturer` (required)::
The property value contains the manufacturer string to be used as part of the MQTT topic, e.g. `Some_Company`.
`vda5050:serialNumber` (required)::
The property value contains the vehicle's unique(!) serial number to be used as part of the MQTT topic, e.g. `AGV-XY-1234`.
`vda5050:rechargeOperation` (optional)::
The property value contains a string that should be used as the vehicle's recharge operation in the plant model, e.g. `Recharge`.
(Default value: `Charge`.)
`vda5050:maxStepsBase` (optional)::
The property value contains the decimal representation of the vehicle's base capacity, i.e. the maximum number of unfinished route steps in the VDA5050 order base that the vehicle can take, e.g. `10`.
(Default value: `2`.)
`vda5050:maxDistanceBase` (optional)::
The property value contains the maximum distance in mm that may be covered by currently queued movement commands.
Once the sum of all currently queued movement commands for a vehicle reaches the defined value, no additional commands are accepted.
(Default value: `Long.MAX_VALUE` (approximately one lightyear))
`vda5050:maxStepsHorizon` (optional)::
The property value contains the decimal representation of the vehicle's horizon capacity, i.e. the maximum number of route steps in the VDA5050 order horizon that the vehicle can take, e.g. `10`.
(Default: unlimited, i.e. all horizon steps on the prospective route.)
`vda5050:minVisualizationInterval` (optional)::
The property value contains the decimal representation of the minimum time in milliseconds between visualization updates forwarded to the kernel, e.g. `1000`.
(Default value: `500`.)
`vda5050:vehicleLengthLoaded` (optional)::
The property value contains the decimal representation of the vehicle length in mm to be set when the vehicle reports at least one load.
(Default value: The vehicle length configured in the plant model.)
`vda5050:vehicleLengthUnloaded` (optional)::
The property value contains the decimal representation of the vehicle length in mm to be set when the vehicle reports no loads.
(Default value: The vehicle length configured in the plant model.)
`vda5050:movementCommandCompletedCondition` (optional)::
The property value contains a string that describes the condition under which a movement command is considered completed.
Valid values are `EDGE` and `EDGE_AND_NODE`.
For details regarding the functionality behind this property, see the 'Movement command completion' section in xref:runtime-behaviour.adoc#movement-command-completion[].
(Default value: `EDGE_AND_NODE`)
`vda5050:extendedDeviationRangePadding` (optional)::
The property value contains a padding distance in m, which is added when a node's deviation range is extended to include the vehicle position.
If the value is negative, it is instead replaced with zero.
(Default value: `0.01`.)
`vda5050:optionalParams.order` (prefix, optional)::
Property keys that start with this prefix should be extended by the path to the optional field in the order message separated by dots.
The property value contains the support status for the optional field, which can be `REQUIRED`, `SUPPORTED`, or `NOT_SUPPORTED`.
(Default value: `SUPPORTED`)

NOTE: If any of the required properties are not set or contain unusable data, the driver may fail to be instantiated for / attached to the vehicle.
